# This is an example docker-compose file to quickly test an IPFS Cluster
# with multiple peers on a contained environment.

# To interact with the cluster use "ipfs-cluster-ctl" (the cluster0 API port is
# exposed to the locahost. You can also "docker exec -ti cluster0 sh" and run
# it from the container. "ipfs-cluster-ctl peers ls" should show all 3 peers a few
# seconds after start.
#
# For persistence, a "compose" folder is created and used to store configurations
# and states. This can be used to edit configurations in subsequent runs. It looks
# as follows:

services:
## Cluster PEER 0 ################################################################
  ipfs0:
    container_name: ipfs0
    image: ipfs/kubo:release
    ports:
     - "4001:4001" # ipfs swarm
     - "5001:5001" # ipfs api
     - "8080:8080" # ipfs gateway
    #  - "4002:4001" # ipfs swarm
    #  - "5002:5001" # ipfs api
    #  - "8081:8080" # ipfs gateway
    volumes:
      - ./compose/ipfs0:/data/ipfs
    networks:
      - personalizada2
      - api-kubo_default

  cluster0:
    container_name: cluster0
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs0
    environment:
      CLUSTER_PEERNAME: cluster0
      CLUSTER_SECRET: "e106519047aabebb55e012316f40537fe1336f5425aed0d7cd9f8a42c94628d5" # From shell variable if set
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs0/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in Cluster
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    ports:
        - "9094:9094" # Open API port (allows ipfs-cluster-ctl usage on host)
        - "9095:9095" # Cluster IPFS Proxy endpoint
        - "9096:9096" # Cluster swarm endpoint
        # - "9090:9094" # Open API port (allows ipfs-cluster-ctl usage on host)
        # - "9091:9095" # Cluster IPFS Proxy endpoint
        # - "9092:9096" # Cluster swarm endpoint
    volumes:
      - ./compose/cluster0:/data/ipfs-cluster
    networks:
      - personalizada2
      - api-kubo_default

## Cluster PEER 1 ################################################################
  ipfs1:
    container_name: ipfs1
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs1:/data/ipfs
    networks:
      - personalizada2
      - api-kubo_default

  cluster1:
    container_name: cluster1
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs1
    environment:
      CLUSTER_PEERNAME: cluster1
      CLUSTER_SECRET: "e106519047aabebb55e012316f40537fe1336f5425aed0d7cd9f8a42c94628d5"
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs1/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster1:/data/ipfs-cluster
    networks:
      - personalizada2
      - api-kubo_default

networks:
  personalizada2:
    driver: bridge
  api-kubo_default:
    driver: bridge