services:
  ipfs2:
    container_name: ipfs2
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs2:/data/ipfs
    ports:
     - "4002:4001" # ipfs swarm
     - "5002:5001" # ipfs api
     - "8081:8080" # ipfs gateway
    networks:
      - personalizada
      - personalizada2

  cluster2:
    container_name: cluster2
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs2
    environment:
      # CLUSTER_PEERNAME: cluster2
      CLUSTER_SECRET: "e106519047aabebb55e012316f40537fe1336f5425aed0d7cd9f8a42c94628d5"
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs2/tcp/5001
      # CLUSTER_CRDT_TRUSTEDPEERS: '*'
      # CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster2:/data/ipfs-cluster
    ports:
        - "9097:9094" # Open API port (allows ipfs-cluster-ctl usage on host)
        - "9098:9095" # Cluster IPFS Proxy endpoint
        - "9099:9096" # Cluster swarm endpoint
    networks:
      - personalizada
      - personalizada2
    command:
      - "daemon --bootstrap /ip4/172.19.0.5/tcp/9096/p2p/12D3KooWR8MxQgHGLF5vx1ShZy3Dkb5ZMjgm5MjVpJaDpi1Qqpwp"

networks:
  personalizada:
    driver: bridge
  personalizada2:
    driver: bridge